# docker-compose.yml
services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile  
    container_name: gateway
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - PYTHONUNBUFFERED=1
      - GATEWAY_HOST=0.0.0.0
      - GATEWAY_PORT=9999
      - BATCH_SIZE=100
      - RABBITMQ_OUTPUT_QUEUE=csv_queue
      - RABBITMQ_INPUT_QUEUE=query_queue

  parser:
    build:
      context: .
      dockerfile: parser/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_QUEUE=csv_queue
      - RABBITMQ_OUTPUT_EXCHANGE=movie_exchange
      - KEEP_COLUMNS=budget,genres,id,original_language,overview,production_countries,release_date,revenue,title

  test_filter_argentina:
    build:
      context: .
      dockerfile: filter/Dockerfile 
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_QUEUE=movie1_queue
      - RABBITMQ_CONSUMER_TAG=argentina
      - RABBITMQ_OUTPUT_QUEUE=deliver_queue
      - RABBITMQ_EXCHANGE=movie_exchange
      - MOVIE_FILTERS=release_date:more(2000);release_date:less(2002);production_countries:in(Argentina)

  test_filter_argentina_2:
    build:
      context: .
      dockerfile: filter/Dockerfile 
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_QUEUE=movie2_queue
      - RABBITMQ_CONSUMER_TAG=argentina_2
      - RABBITMQ_OUTPUT_QUEUE=deliver_queue_2
      - RABBITMQ_EXCHANGE=movie_exchange
      - MOVIE_FILTERS=release_date:more(2000);release_date:less(2002);production_countries:in(Argentina)
  deliver:
    build:
      context: .
      dockerfile: deliver/Dockerfile
    container_name: deliver
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_QUEUE=deliver_queue
      - RABBITMQ_OUTPUT_QUEUE=query_queue
      - KEEP_COLUMNS=genres,title

  deliver_2:
    build:
      context: .
      dockerfile: deliver/Dockerfile
    container_name: deliver_2
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_QUEUE=deliver_queue_2
      - RABBITMQ_OUTPUT_QUEUE=query_queue
      - KEEP_COLUMNS=genres,title

  client:
    build:
      context: .
      dockerfile: client/Dockerfile  # Apunta al Dockerfile en client/
    container_name: client
    depends_on:
      - gateway
    networks:
      - app-network
    environment:
      - PYTHONUNBUFFERED=1
      - GATEWAY_HOST=gateway
      - GATEWAY_PORT=9999
    deploy:
      restart_policy:
        condition: none

networks:
  app-network:
    driver: bridge