services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
    - 5672:5672
    - 15672:15672
    healthcheck:
      test:
      - CMD
      - rabbitmqctl
      - status
      interval: 10s
      timeout: 5s
      retries: 5
    
    
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: gateway
    depends_on:
      rabbitmq:
        condition: service_healthy
    
    
    environment:
    - PYTHONUNBUFFERED=1
    - GATEWAY_HOST=0.0.0.0
    - GATEWAY_PORT=9999
    - BATCH_SIZE=100
    - RABBITMQ_OUTPUT_QUEUE=csv_queue
    - RABBITMQ_INPUT_QUEUE=query_queue
  parser:
    build:
      context: .
      dockerfile: parser/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    
    
    environment:
    - PYTHONUNBUFFERED=1
    - RABBITMQ_QUEUE=csv_queue
    - RABBITMQ_OUTPUT_EXCHANGE=files
    - KEEP_MOVIES_COLUMNS=budget,genres,id,original_language,overview,production_countries,release_date,revenue,title
    - KEEP_RATINGS_COLUMNS=userId,movieId,rating
  
  unique_country:
    build:
      context: .
      dockerfile: filter/Dockerfile 
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_QUEUE=movie2_queue
      - RABBITMQ_CONSUMER_TAG=argentina_2
      - RABBITMQ_OUTPUT_QUEUE=country_router
      - RABBITMQ_EXCHANGE=files
      - RABBITMQ_ROUTING_KEY=movies_metadata.csv
      - MOVIE_FILTERS=production_countries:count(1)
 
  router:
    build:
      context: .
      dockerfile: router/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    
    
    environment:
    - PYTHONUNBUFFERED=1
    - RABBITMQ_QUEUE=country_router
    - RABBITMQ_CONSUMER_TAG=router_0
    - RABBITMQ_OUTPUT_EXCHANGE=country_calculator
    - NUMBER_OF_NODES=2

  calculator:
    build:
      context: .
      dockerfile: calculator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy

    environment:
    - PYTHONUNBUFFERED=1
    - RABBITMQ_QUEUE=queue
    - NODE_ID=0
    - RABBITMQ_EXCHANGE=country_calculator
    - RABBITMQ_CONSUMER_TAG=consumer
    - RABBITMQ_OUTPUT_QUEUE=deliver_queue
    - OPERATION=sum_by:production_countries,budget
    - RABBITMQ_EXCHANGE_TYPE=direct

  calculator_2:
    build:
      context: .
      dockerfile: calculator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - PYTHONUNBUFFERED=1
    - RABBITMQ_QUEUE=queue
    - NODE_ID=1
    - RABBITMQ_EXCHANGE=country_calculator
    - RABBITMQ_CONSUMER_TAG=consumer2
    - RABBITMQ_OUTPUT_QUEUE=deliver_queue
    - OPERATION=sum_by:production_countries,budget
    - RABBITMQ_EXCHANGE_TYPE=direct

  deliver:
    build:
      context: .
      dockerfile: deliver/Dockerfile
    container_name: deliver
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - PYTHONUNBUFFERED=1
    - RABBITMQ_QUEUE=deliver_queue
    - RABBITMQ_OUTPUT_QUEUE=query_queue
    - SORT=total:5
    - KEEP_COLUMNS=value,total
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: client
    depends_on:
    - gateway
    
    
    environment:
    - PYTHONUNBUFFERED=1
    - GATEWAY_HOST=gateway
    - GATEWAY_PORT=9999
    deploy:
      restart_policy:
        condition: none
